spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final
    username: root
    password: 321000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    log-resolved-exception: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
logging:
  file:
    name: final.log
management:
  endpoints:
    web:
      base-path: /monitor
